Supplier_Directory/FrontEnd/Controllers/ListingsController.cs
using Frontend.Helpers;
using Frontend.Helpers.Authorise;
using Frontend.Models;
using GoogleMaps.LocationServices;
using SD.Core.Common;
using SD.Core.Common.Config;
using SD.Core.Common.Constants;
using SD.Core.Common.Utils;
using SD.Core.Data;
using SD.Core.Data.Model;
using SD.Core.Data.Model.HS;
using SD.Core.Services.Core;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace Frontend.Controllers
{
    public class ListingsController : BaseController
    {
        private IMongoRepository1 mongoRepository;
        public readonly CountryService _countryService;
        public readonly TagsService _tagsService;
        public readonly MemberService _memberService;
        public readonly ListingService _listingService;
        public readonly RegionService _regionService;
        public readonly MediaService _mediaService;
        private readonly SponsoredListingService _sponsoredListingService;
        private const int _pageSize = 10;
        public RegionHydrationSettings _regionHydrationSettings = new RegionHydrationSettings() { Countries = new CountryHydrationSettings() };
        public TagHydrationSettings _tagHydrationSettings = new TagHydrationSettings() { ParentTag = new TagHydrationSettings() };
        public ListingHydrationSettings _listingHydrationSettings = new ListingHydrationSettings()
        {
            PrimaryMedia = new MediaHydrationSettings(),
            RelatedMedia = new MediaHydrationSettings(),
            RelatedTags = new TagHydrationSettings(),
            Country = new CountryHydrationSettings()
        };
        private readonly SD.Core.Data.Model.HS.SponsoredListingHydrationSettings _sponsoredListingHydrationSettings =
            new SD.Core.Data.Model.HS.SponsoredListingHydrationSettings { RelatedTags = new SD.Core.Data.Model.HS.TagHydrationSettings(), RelatedListings = new SD.Core.Data.Model.HS.ListingHydrationSettings() };

        public ListingsController()
        {
            mongoRepository = AppKernel.GetInstance<IMongoRepository1>();
            _countryService = new CountryService(mongoRepository);
            _tagsService = new TagsService(mongoRepository);
            _listingService = new ListingService(mongoRepository);
            _regionService = new RegionService(mongoRepository);
            _mediaService = new MediaService(mongoRepository);
            _sponsoredListingService = new SponsoredListingService(mongoRepository);
        }

        public ListingsController(IMongoRepository1 _mongoRepository)
        {
            this.mongoRepository = _mongoRepository;
            _countryService = new CountryService(_mongoRepository);
            _tagsService = new TagsService(_mongoRepository);
            _memberService = new MemberService(_mongoRepository);
            _listingService = new ListingService(_mongoRepository);
            _regionService = new RegionService(_mongoRepository);
            _mediaService = new MediaService(_mongoRepository);
            _sponsoredListingService = new SponsoredListingService(mongoRepository);
        }

        //
        // GET: /Listings/

        public ActionResult Index()
        {
            Results(null, null, null, null);
            return View();
        }

        public ActionResult Results(string keyword, string countryName, string categoryName, string categoryUrl, int page = 1, string submit = "search")
        {
            ListingResultViewModel model = new ListingResultViewModel();
            string countryId = "", categoryId = "";
            List<string> tags = new List<string>();

            #region SearchFilter
            if (submit == "search")
            {
                //get countries
                if (!string.IsNullOrEmpty(countryName))
                {
                    var country = _countryService.FindByName(countryName);
                    if (country != null)
                        countryId = country.Id;
                    model.SearchFilter.Location = country;
                }
                //get category
                if (!string.IsNullOrEmpty(categoryName))
                {
                    var tag = _tagsService.FindByDisplayText(categoryName);
                    if (tag != null)
                    {
                        categoryId = tag.Id;
                        tags = _tagsService.GetChildTags(categoryId);
                        tags.Add(categoryId);
                    }
                    model.SearchFilter.Category = tag;
                }

                model.SearchFilter.Keyword = keyword;

                //Brings back listings with the featured ones first.
                IList<SD.Core.Data.Model.Listing> listings = _listingService.Search(tags, countryId, keyword, 0, 0, true, true, _listingHydrationSettings, true);                
                model.Results = listings.ToList();
                var resultsPage = model.Results.ToPagedList(page, _pageSize);
                ViewBag.ResultsPage = resultsPage;

                //set the filter defaults
                model.BrowseFilter.Tags = _tagsService.All().Where(x => string.IsNullOrEmpty(x.ParentId)).ToList();
                model.BrowseFilter.Regions = _regionService.GetAllRegions(_regionHydrationSettings);
            }
            #endregion

            #region BrowseFilter    
            if (submit == "browse")
            {
                //check if a filter is selected
                if (Request.QueryString["t"] != null || Request.QueryString["c"] != null || Request.QueryString["r"] != null)
                {
                    string tagQuery = Request.QueryString["t"];
                    string countryQuery = Request.QueryString["c"];
                    string regionQuery = Request.QueryString["r"];

                    #region search selected countries
                    string[] searchCountriesQuery = string.IsNullOrEmpty(countryQuery) ? new string[] { } : countryQuery.Split(' ').Where(x => !string.IsNullOrEmpty(x)).ToArray();
                    string[] searchRegionsQuery = string.IsNullOrEmpty(regionQuery) ? new string[] { } : regionQuery.Split(' ').Where(x => !string.IsNullOrEmpty(x)).ToArray();
                    List<string> searchCountries = new List<string>();

                    if (searchRegionsQuery.ToList().Count > 0 || searchCountriesQuery.ToList().Count > 0)
                    {
                        foreach (var r in searchRegionsQuery.ToList())
                        {
                            var region = _regionService.FindBySlug(r, _regionHydrationSettings);
                            var browseCountries = region.Countries;
                            if (browseCountries.Count > 0)
                            {
                                var browseCountryStrings = browseCountries.Select(x => x.Id);
                                searchCountries.AddRange(browseCountryStrings);
                            }
                            //set filter countries
                            foreach (var browseCountry in browseCountries)
                            {
                                if (!searchCountriesQuery.ToList().Exists(x => x == browseCountry.UrlSlug))
                                    model.BrowseFilter.Countries.Add(browseCountry);
                            }
                            //set the selected countries
                            model.BrowseFilter.SelectedRegions.Add(region);
                        }
                        foreach (var c in searchCountriesQuery.ToList())
                        {
                            var country = _countryService.FindBySlug(c, null);

                            if (!searchCountriesQuery.ToList().Exists(x => x == country.UrlSlug))
                                model.BrowseFilter.Countries.Add(country);

                            if (c == searchCountriesQuery.Last())
                                searchCountries.Add(country.Id);

                            //set the selected countries
                            model.BrowseFilter.SelectedCountries.Add(country);
                        }
                    }
                    else
                        model.BrowseFilter.Regions = _regionService.GetAllRegions(_regionHydrationSettings);
                    #endregion
                    #region search selected tags
                    string[] searchtagsQuery = string.IsNullOrEmpty(tagQuery) ? new string[] { } : tagQuery.Split(' ').Where(x => !string.IsNullOrEmpty(x)).ToArray();
                    List<string> searchtags = new List<string>();
                    //if there is a tags query
                    if (searchtagsQuery.ToList().Count > 0)
                    {
                        foreach (var t in searchtagsQuery)
                        {
                            var tag = _tagsService.FindByUrlSlug(t);
                            var browseTags = _tagsService.GetChildTags(tag.Id, null);
                            //add child tags
                            if (browseTags.Count > 0)
                            {
                                var browsetagStrings = browseTags.Select(x => x.Id);
                                //set search tags
                                //only get the last tag. e.g business consultant in consultant+ business consultant                             
                                if (t == searchtagsQuery.Last())
                                    searchtags.AddRange(browsetagStrings);
                            }

                            //set search tags
                            //only get the last tag. e.g business consultant in consultant+ business consultant                             
                            if (t == searchtagsQuery.Last())
                                searchtags.Add(tag.Id);

Supplier_Directory/FrontEnd/Controllers/TagsController.cs
using SD.Core.Common;
using SD.Core.Data;
using SD.Core.Data.Model;
using SD.Core.Data.Model.HS;
using SD.Core.Services.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    public class TagsController : Controller
    {
        // GET: Tags
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PopularTags(int take)
        {
            IMongoRepository1 mongoRepository = AppKernel.GetInstance<IMongoRepository1>();
            TagHydrationSettings settings = new TagHydrationSettings() { ParentTag = new TagHydrationSettings() };
            TagsService tagsService = new TagsService(mongoRepository);
            var tags = tagsService.GetPopularTags(take, settings);
            ViewBag.PopularCategories = tags.OrderByDescending(x => x.DisplayText);
            return PartialView("PopularTags");
        }
    }
}

Supplier_Directory/FrontEnd/Views/Shared/Error404.cshtml
@{
    ViewBag.Title = "404";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="home-search">
        <div class="container">

            <h1>Page not found</h1>

            <div class="clear"></div>


           

            <div>
                <p>Unfortunately, we haven't been able to find the page you are looking for.</p>
                <p>
                    If you typed in a URL, please make sure you have entered it correctly. It is also
                    possible that the page you are looking for has been moved or deleted.
                </p>
                <p>Return to the <a href="/">homepage</a></p>
            </div>



        </div>






    </div>

</div>

Supplier_Directory/FrontEnd/Views/Shared/GotItCount.cshtml
@model SD.Core.Data.DTOs.GotItStat
<label class="btn btn-success btn-lg">
    <input type="checkbox" autocomplete="off" checked>
    <i class="fa fa-thumbs-up"></i>
    I have got it
    <input type="button" id="btnYes" value="Yes" />
</label>
<label class="btn btn-danger btn-lg ">
    <input type="checkbox" autocomplete="off">
    <i class="fa fa-thumbs-down"></i>
    I have not got it
    <input type="button" id="btnNo" value="No" />
</label>
@if (Model == null)
{
<script>
    $("#btnYes").click(function () {
            GotIt(1);
    });
    $("#btnNo").click(function () {
            GotIt(0);
    });
</script>
}
else
{
    <script>
    $("#btnYes").click(function () {

            alert("You have already rated this item");
    });
    $("#btnNo").click(function () {

            alert("You have already rated this item");
    });
    </script>
}

Supplier_Directory/FrontEnd/Views/Shared/LatestListings.cshtml
@model Frontend.Models.ListingResultViewModel
@if (Model.LatestListings.Count > 0)
{
    <h2>Latest listings</h2>    
    <div class="listing row">
        @foreach (var listing in Model.LatestListings)
        {
            <h5>@listing.CompanyName</h5>
            <div class="col-md-12">
                <a href="/listings/detail/@listing.UrlSlug" class="btn btnsec pull-right">Details</a>
            </div>
        }
    </div>    
}

Supplier_Directory/FrontEnd/Views/Shared/Pages.cshtml
@using SD.Core.Common.Constants
@using SD.Core.Common.Extensions
@using SD.Core.Common.Utilities
@using SD.Core.Common.Utilities.Extensions.Html
@using SD.Core.Services.Core
@using Frontend.Helpers;
@model System.Collections.Generic.IList<SD.Core.Data.Model.Article>

@if (Model.Any())
{
    <h4>
        Related Pages
    </h4>

    <ul class="related-pages list-unstyled">
        @foreach (var item in Model)
        {
            var url = ArticleUtilities.GetArticleUri(item);
            <li>
                <a href="@url">
                    @item.Title
                    <span>
                        @Html.DateFormat(item.LiveFrom)
                    </span>
                </a>
            </li>

        }
    </ul>
}

Supplier_Directory/FrontEnd/Views/Shared/PopularTags.cshtml
@if (ViewBag.PopularCategories != null)
{
    foreach (SD.Core.Data.Model.Tags tag in ViewBag.PopularCategories)
    {
        <li><a href="/listings/category?submit=browse&categoryurl=@tag.UrlSlug">@tag.DisplayText</a></li>
        @*<li><a href="/listings/results?categoryName=@tag.UrlSlug">@tag.DisplayText</a></li>*@
    }
}

Supplier_Directory/FrontEnd/Views/Shared/RelatedTags.cshtml
@using Frontend.Models
@model RelatedTagsModel

<button class="btn btn-default btn-lg collapsed" data-toggle="collapse" data-target="#relatedtagscollapse">
    <i class="fa fa-tags"></i>
    <span>
        Related topics
    </span>
</button>

<div id="relatedtagscollapse" class="collapse">

    <div class="col-md-12 row buttons">

        <h4>
            Filter your content
        </h4>

        <p>
            Refine your content by clicking on one of the topics below, or type to find the subject you are after.
        </p>

        <div class="clearfix"></div>

        <div class="form-group">
            <input autocomplete="off" class="form-control" data-bind="value: query, valueUpdate: 'keyup'" placeholder="Start typing to filter Topics" />
        </div>

        <div class="clearfix"></div>

        <div class="row" id="relatedtags">

            <!-- ko ifnot: query() === "" -->
            <div class="panel-teaser">
                <!-- ko if: searchResults().length > 0 -->
                <div class="btn-group" data-bind="foreach: searchResults">

                    <!-- ko if: tagSlug !== '@Model.filter' -->
                    <a class="btn btn-default" href="/hub/" data-bind="attr : { 'href' : '/hub/' + '@Model.filter' + '+' + tagSlug, 'title' : 'View Topics labelled ' + tagName }">
                        <i class="fa fa-plus"></i>
                        <!-- ko text: tagName --><!-- /ko -->
                        <span>
                            (<!-- ko text: tagCount --><!-- /ko -->)
                        </span>
                    </a>
                    <!-- /ko -->
                </div>
                <!-- /ko -->
                <!-- ko ifnot: searchResults().length > 0 -->
                <div class="alert alert-info hide" role="alert" data-bind="attr: { 'class' : query() !== '' ? 'alert alert-info' : 'alert alert-info hide' }">
                    No Topics were found. Please refine your search.
                </div>
                <!-- /ko -->
            </div>
            <!-- /ko -->
            <!-- ko if: query() === ""  -->
            <div class="panel-teaser">
                <div class="btn-group">
                    <!-- ko foreach: searchResults -->
                    <!-- ko if: $index() <= 9 -->
                    <!-- ko if: tagSlug !== '@Model.filter' -->
                    <a class="btn btn-default" href="/hub/" data-bind="attr : { 'href' : '/hub/' + '@Model.filter' + '+' + tagSlug, 'title' : 'View Topics labelled ' + tagName }">
                        <i class="fa fa-plus"></i>
                        <!-- ko text: tagName --><!-- /ko -->
                        <span>
                            (<!-- ko text: tagCount --><!-- /ko -->)
                        </span>
                    </a>
                    <!-- /ko -->
                    <!-- /ko -->
                    <!-- /ko -->
                    <!-- ko if: query() === ""  -->
                    <!-- ko if: searchResults().length > 9 -->
                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#relatedTagsModal">
                        View more related topics &nbsp;
                        <span class="glyphicon glyphicon-modal-window" aria-hidden="true"></span>
                    </button>
                    <!-- /ko -->
                    <!-- /ko -->
                </div>
            </div>
            <!-- /ko -->
        </div>

    </div>

</div>

<!-- ko if: query() === ""  -->
<!-- ko if: searchResults().length > 9 -->
<!-- Modal -->
<div class="modal fade" id="relatedTagsModal" tabindex="-1" role="dialog" aria-labelledby="relatedTagsModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h1 class="modal-title">
                    View more Related Topics
                </h1>
            </div>
            <div class="modal-body">
                <!-- ko foreach: searchResults -->
                <!-- ko if: $index() > 9 -->
                <!-- ko if: tagSlug !== '@Model.filter' -->
                <a class="btn btn-default" href="/hub/" data-bind="attr : { 'href' : '/hub/' + '@Model.filter' + '+' + tagSlug, 'title' : 'View Topics labelled ' + tagName }">
                    <i class="fa fa-plus"></i>
                    <!-- ko text: tagName --><!-- /ko -->
                    <span>
                        (<!-- ko text: tagCount --><!-- /ko -->)
                    </span>
                </a>
                <!-- /ko -->
                <!-- /ko -->
                <!-- /ko -->
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<!-- /ko -->
<!-- /ko -->

<script type="text/javascript">

    var relatedTags = {};
    relatedTags.tagsUrl = '/hub/getrelatedtags/@Model.filter';
    relatedTags.existingFilter = '@Model.filter';

</script>

Supplier_Directory/FrontEnd/Views/Shared/SearchListings.cshtml
@model Frontend.Models.ListingResultViewModel


@using (Html.BeginForm("Results", "Listings", FormMethod.Post, new { name = "editForm", @class = "form-inline" }))
{
    <div class="form-group">
        <input type="text" class="form-control" id="keyword" name="keyword" placeholder="Keyword" value="@Model.SearchFilter.Keyword">
    </div>
                    <div class="form-group">
                        @if (Model.SearchFilter.Location != null)
                        {
                             <input type="text" class="form-control" id="location" name="countryName" placeholder="location" value="@Model.SearchFilter.Location.Name">
                             <input type="hidden" id="countryId" name="countryId" value=""/>
                        }
                        else
                        {
                            <input type="text" class="form-control" id="location" name="countryName" placeholder="location" >
                            <input type="hidden" id="countryId" name="countryId" />
                        }
                    </div>
                    <div class="form-group">
                        @if (Model.SearchFilter.Category != null)
                        {
                            <input type="text" class="form-control" id="category" name="categoryName" placeholder="Category" value="@Model.SearchFilter.Category.DisplayText">
                            <input type="hidden" id="categoryId" name="categoryId" value="" />
                        }
                        else
                        {
                            <input type="text" class="form-control" id="category" name="categoryName" placeholder="Category">
                            <input type="hidden" id="categoryId" name="categoryId" />
                        }
                    </div>
                    <button type="submit" name="submit" value="search" class="btn btn-primary">Search Companies</button>
                    @*@if (Model.Category != null)
                    {
                        <input type="hidden" id="countryId" name="countryId" />
                    }
                    else
                    {
                    }
                    <input type="hidden" id="categoryId" name="categoryId" />*@
}

Supplier_Directory/FrontEnd/Views/Shared/UserResponses.cshtml
@using SD.Core.ViewModels
@model IList<UserResponseItem>

@if (Model != null && Model.Count != 0)
{
    <ul class="list-unstyled" id="userResponses">
        @foreach (var response in Model)
        {
            var alertClass = "";
            switch (response.Type)
            {
                case ResponseType.Error:
                    alertClass = "alert-error";
                    break;
                case ResponseType.Warning:
                    alertClass = "";
                    break;
                case ResponseType.Notice:
                    alertClass = "alert-success";
                    break;
            }
            <li class="alert @alertClass">
                <a href="#" class="close" data-dismiss="alert">×</a>
                <span class="headline">@response.Headline</span>
                <p>@response.Details</p>
            </li>
        }
    </ul>
}

Supplier_Directory/FrontEnd/Views/Shared/_FeaturedListing.cshtml
@using SD.Core.Data.Model
@using SD.Core.Common.Constants
@using SD.Core.Common.Utilities.Extensions.Html
@using Frontend.Helpers.HtmlExtensions
@model Frontend.Models.ListingResultViewModel
@foreach (var featuredListing in Model.FeaturedListings)
{    
<div class="row">
    <div class="container">
        <div class="col-md-8 col-xs-12 offset-top-20">
            <div class="listing row">
                <h2 class="col-md-8">@featuredListing.RelatedListing.CompanyName</h2>
                <div class="col-md-4">
                    @if (featuredListing.RelatedListing.PrimaryMedia != null)
                    {
                        <img src="@Html.GetMediaUri(MediaProfile.size_600x300, featuredListing.RelatedListing.PrimaryMedia)" alt="@featuredListing.RelatedListing.PrimaryMedia.Title" title="@featuredListing.RelatedListing.PrimaryMedia.Title" class="edit-media-item-image img-responsive" /><br />
                    }
                </div>
                <div class="col-md-12">
                    <a href="/listings/detail/@featuredListing.RelatedListing.UrlSlug" class="btn btn-primary pull-right">Details</a>
                   @Html.Raw(featuredListing.RelatedListing.StandFirst)
                </div>

            </div>
        </div>
    </div>
</div>
}

Supplier_Directory/FrontEnd/Views/Shared/_Layout.cshtml
@using Frontend.Helpers.HtmlExtensions
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Assets/Styles/bootstrap/bootstrap-3.3.6-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/Styles/bootstrap/bootstrap-3.3.6-dist/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Assets/Styles/font-awesome/font-awesome-4.5.0/css/font-awesome.min.css?v=1234" rel="stylesheet" />
    <link href="~/Assets/Styles/custom/layout.css" rel="stylesheet" />
    <link href="~/Assets/Fonts/webfonts/fonts.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Assets/Styles/custom/print.css" type="text/css" media="print">
    <link href="~/Assets/Scripts/jquery-ui-1.11.4.custom/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Assets/Scripts/jquery-ui-1.11.4.custom/jquery-ui.theme.min.css" rel="stylesheet" />
    <link href="~/Assets/Scripts/jquery-ui-1.11.4.custom/jquery-ui.structure.min.css" rel="stylesheet" />

    <script src="~/Assets/Scripts/jquery.js" type="text/javascript"></script>
    <script src="~/Assets/Scripts/bootstrap.js" type="text/javascript"></script>
    <script src="~/Assets/Scripts/jquery-ui-1.11.4.custom/jquery-ui.min.js" type="text/javascript"></script>
    @*<script src="~/Assets/Scripts/jquery/jquery-2.2.0.js"></script>*@
    <script>window.jQuery || document.write('<script src="~/Assets/Scripts/jquery/jquery-2.2.0.js"><\/script>')</script>
    @*<script src="~/Assets/Styles/bootstrap/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>*@
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    @RenderSection("Head", false)
</head>
<body>

    <!-- Static navbar -->
    <div class="nav-top clearfix">
        <div class="col-md-2">
            <img src="~/Assets/Images/logo.png" alt="" class="logo img-responsive" />
        </div>
        <ul class="nav navbar-nav navbar-right">
            @Html.Partial("_LoginPartial")
            @*<li><a href="/">Favourites<span class="sr-only">(current)</span></a></li>
            <li><a href="/Profile/Index">My Account (Sign in)</a></li>
            <li><a href="/Profile/register">Register</a></li>*@
        </ul>

    </div>

    <nav class="navbar navbar-default clearfix">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse Categories<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      @{  Html.RenderAction("PopularTags", "Tags", new { take = 10 }); }
                    </ul>
                    <li class="@Html.IsActiveMenu(actions: "Index", controllers: "Home")"><a href="/">Home</a></li>
                    <li class="@Html.IsActiveMenu(actions: "Results", controllers: "Listings")"><a href="/listings/results">View all listings</a></li>
                    <li class="@Html.IsActiveMenu(actions: "Post", controllers: "Listings")"><a href="/listings/post">Post a listing</a></li>
                    <li class="@Html.IsActiveMenu(actions: "About", controllers: "Home")"><a href="/about">About directory</a></li>
                    <li class="@Html.IsActiveMenu(actions: "ListWithUs", controllers: "Listings")"><a href="/listings/listwithus">Listing with us</a></li>
                </ul>
 
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

                @RenderBody()
 
    <div class="container body-content">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Suppliers Directory <a href="/Home/TermsAndConditions">Terms and Conditions</a></p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
        
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

</body>
</html>
@*<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxN-_4qF8gcfuX7tOBs5w6Wo-RIxnYSrc"></script>*@  