Supplier_Directory/CMS/Models/MemberViewModel.cs
using SD.Core.Common.Constants;
using SD.Core.Data.Model;
using SD.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CMS.Models
{
    [Serializable]
    public class MemberListModel
    {
        public IList<Member> Members = new List<Member>();
        public IList<Member> PublishedMembers = new List<Member>();
        public PaginationModel Pagination;
        public IList<UserResponseItem> Responses = new List<UserResponseItem>();
        public IList<Listing> Listing = new List<Listing>();        
        public bool ShowDeletedMembers = false;

        public PublicationStatus FilterType;
        public string SearchText;
        public int TotalSearchResults;
        public IList<Member> SearchResults;

        //public IList<Member> AreaFeatured { get; set; }
    }

    [Serializable]
    public class MemberEditModel
    {
        public Member Member;
        public Test Test;
        //public IList<VersionWrapper> VersionHistory;
        public IList<UserResponseItem> Responses = new List<UserResponseItem>();
        //public IList<string> Categories = new List<string>();
        //public User CreatedBy;
        //public User UpdatedBy;
        //public int ViewCount;
        //public bool Versioned;        

        //public string AuthorAuthenticatedUserName;
        //public string AuthorAuthenticatedUserId;
        public MemberEditModel(Member member)
        {
            Member = member;
        }

        public MemberEditModel()
        {

        }
    }
}

Supplier_Directory/CMS/Controllers/MembersController.cs
using AutoMapper;
using CMS.Helpers;
using CMS.Models;
using SD.Core.Common;
using SD.Core.Common.Constants;
using SD.Core.Data;
using SD.Core.Data.Model;
using SD.Core.Data.Model.HS;
using SD.Core.Services.Core;
using SD.Core.Services.Security;
using SD.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.Controllers
{
    public class MembersController : Controller
    {        
        private const string PaginationMainIndexInstanceKey = "MemberMainIndex";

        private const string UserResponseInstanceKey = "Member";

        private const string PaginationBaseUrl = "/Members/";
        private const string MemberSearchTextCacheKey = "MemberSearchTextCache";
        private const string MemberSearchCountCacheKey = "MemberSearchCountCache";
        private const int MaxResultsPerTabView = 5;
        // Helpers
        private readonly PaginationHelper _mainlistPageHelper;

        //Carries Messages
        private readonly UserResponseHelper _responseHelper;

        //database entity
        private IMongoRepository1 mongoRepository;

        //
        private readonly MemberService _memberService;

        //
        private readonly ListingService _listingService;

        //
        private readonly UserService _userService;
        //        

        public readonly CountryService _countryService;
        // Hydration settings
        private static readonly MemberHydrationSettings _memberHydrationSettings;
        private int SearchCount
        {
            get
            {
                if (Session[MemberSearchCountCacheKey] == null)
                    Session[MemberSearchCountCacheKey] = MaxResultsPerTabView;
                return (int)Session[MemberSearchCountCacheKey];
            }
            set
            {
                Session[MemberSearchCountCacheKey] = value;
            }
        }

        static MembersController()
        {
            _memberHydrationSettings = new MemberHydrationSettings
            {
                MemberListings = new ListingHydrationSettings(),
                 Country = new CountryHydrationSettings(),
                  UpdatedBy = new UserHydrationSettings()
            };
        }

        public MembersController()
        {
            mongoRepository = AppKernel.GetInstance<IMongoRepository1>();

            _listingService = new ListingService(mongoRepository);

            //_savedSearchService = new SavedSearchService(mongoRepository);
            _memberService = new MemberService(mongoRepository);

            _userService = new UserService(mongoRepository);
            

            _mainlistPageHelper = new PaginationHelper(PaginationMainIndexInstanceKey, PaginationBaseUrl);
            _responseHelper = new UserResponseHelper(UserResponseInstanceKey);
            _countryService = new CountryService(mongoRepository);
        }

        public MembersController(IMongoRepository1 _mongoRepository)
        {
            this.mongoRepository = _mongoRepository;

            _listingService = new ListingService(mongoRepository);

            //_savedSearchService = new SavedSearchService(mongoRepository);

            _userService = new UserService(mongoRepository);
            _memberService = new MemberService(mongoRepository);

            _mainlistPageHelper = new PaginationHelper(PaginationMainIndexInstanceKey, PaginationBaseUrl);
            _responseHelper = new UserResponseHelper(UserResponseInstanceKey);
            _countryService = new CountryService(mongoRepository);
        }

        //
        // GET: /Members/
        [CMSAuthorize("UseCMS & ViewMembers | EditMembers")]
        public ActionResult Index()
        {
            return Page(-1);
            //return View();
        }


        [CMSAuthorize("UseCMS & ViewMembers | EditMembers")]
        public ActionResult Page(int page = -1)
        {

            bool unmoderated = false;
            if (page != -1)
            {
                _mainlistPageHelper.SetPage(page);
            }
            
            var model = new MemberListModel { FilterType = PublicationStatus.Published };
            PublicationStatus[] showWithStatus;

            if (Request.QueryString["unmoderated"] != null)                            
            {
                unmoderated = true;
                showWithStatus = new[] { PublicationStatus.UnPublished };
            }
            else
                showWithStatus = new[] { PublicationStatus.Published, PublicationStatus.UnPublished };

            var hydrationSettings = new MemberHydrationSettings
            {
                MemberListings = new ListingHydrationSettings()
            };

            int skip = _mainlistPageHelper.PaginationModel.PageSize * (_mainlistPageHelper.PaginationModel.CurrentPage - 1);
            int take = _mainlistPageHelper.PaginationModel.PageSize;
            List<Member> results = new List<Member>();
            if (unmoderated)
            {
                results = _memberService.GetAllMembers().Where(x => x.IsModerated == false).ToList();
                _mainlistPageHelper.SetTotalItemCount(results.Count);                
                results = results.Skip(skip).Take(take).ToList();
                model.Members = results.OrderByDescending(x => x.CreatedOn).ToList();

                _mainlistPageHelper.PaginationModel.QueryString = "?unmoderated=true";
            }
            else
            {
                results = _memberService.GetAllMembers().Where(x => x.Status == PublicationStatus.Published || x.Status == PublicationStatus.UnPublished).ToList();
                _mainlistPageHelper.SetTotalItemCount(results.Count);
                results = results.Skip(skip).Take(take).ToList();
                model.Members = results.OrderByDescending(x => x.UpdatedOn).ToList();
            }

            
            // Put the view model together
            

            model.Pagination = _mainlistPageHelper.PaginationModel;
            model.Pagination.BaseUrl = PaginationBaseUrl;           
            model.Responses = _responseHelper.UserResponses;
            model.ShowDeletedMembers = ShowDeletedMembers;

            // If a search was previously made then reload the results
            if (string.IsNullOrWhiteSpace(SearchText)) return View("Index", model); 
            model.SearchText = SearchText;

            var searchCount = 30; //todo remove later
            model.SearchResults = search(SearchText, 0, searchCount);

            //model.SearchResults = model.ToList();

            return View("Index", model);
        }

        [CMSAuthorize("UseCMS & ViewMembers | EditMembers")]
        public ActionResult Edit(string id)
        {
            using (var editCache = new EntityEditCache<Member>(x => x.Id))
            {
                var model = new MemberEditModel { Member = _memberService.GetById(id, _memberHydrationSettings) };

                if (model.Member == null)
                {
                    _responseHelper.AddUserResponse(ResponseType.Error, "Could not find the specified member to edit");
                    model.Responses = _responseHelper.UserResponses;
                    return RedirectToAction("Index");
                    //return View("Index", getListingModel(-1));
                }
                ViewBag.Countries = _countryService.GetCountries().Select(x => new SelectListItem
                {
                    //Value = x.Id,
                    Value = x.Id, //temporarily use country name as value field till the Member model support countryId
                    Text = x.Name,
                    Selected = (model.Member.Id == x.Id)
                }).ToList();
                editCache.SetEntity(model.Member);
                model.Responses = _responseHelper.UserResponses;
                return View("Edit", model);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditAction(Member member, string submit, string[] tags)
        {
            if (submit.ToLower() == "cancel")
                return RedirectToAction("Index");
            else if (submit.ToLower() == "save")
            {
                using (var editHelper = new EntityEditCache<Member>(x => x.Id))
                {
                   List<Member> duplicates = _memberService.GetAllMembers().Where(x => x.Email == member.Email && member.Id != x.Id).ToList();
                    if(duplicates.Count > 0)
                    {
                        foreach (var dup in duplicates)
                        {
                            _responseHelper.AddUserResponse(ResponseType.Error, string.Format("This email address is already in use by the member: <a href='/Member/edit?id={0}' target='blank'> {1} {2}</a>", 
                                dup.Id, dup.Firstname, dup.Surname));
                        }
                        var model = new MemberEditModel();
                        model.Responses = _responseHelper.UserResponses;
                        return View("Edit", model);
                    }
                    mergeBasicChanges(member, editHelper, member.Id);

                    MemberEditModel editModel = new MemberEditModel();
                    editModel.Member = editHelper.GetEntity(member.Id);
                    editModel.Member.UpdatedBy = MembershipHelper.GetActiveUser();
                    editModel.Member.UpdatedOn = DateTime.Now;               
                    _memberService.Save(editModel.Member);
                    
                    //get back te successful response message
                    _responseHelper.AddUserResponse(ResponseType.Notice, string.Format("Successfully updated the member: {0} {1}", editModel.Member.Firstname, editModel.Member.Surname));                    
                    editModel.Responses = _responseHelper.UserResponses;

Supplier_Directory/CMS/Views/Members/Edit.cshtml
@using CheckBoxList.Mvc.Html
@using CMS.Models
@using CMS.Helpers
@using SD.Core.Common.Config
@using SD.Core.Common.HtmlExtensions
@using SD.Core.Data.Model
@using SD.Core.Common.Constants
@using SD.Core.Services.Security
@using ScriptRegistrar = SD.Core.Common.Utils.ScriptRegistrar
@using SD.Core.Common.Utilities

@model CMS.Models.MemberEditModel

@{
    ViewBag.Title = "Editing Member";
    Layout = "~/Views/Shared/_Layout.cshtml";
  
}

@section SideBar
{
    <li class="nav-header">
        Actions
    </li>
    <li role="presentation">
        <a href="/Members">
            <i class="fa fa-chevron-left"></i>
            Back to member list
        </a>
    </li>

    <li class="divider"></li>

    <li role="presentation" class="active">
        <a href="#info" aria-controls="home" role="tab" data-toggle="tab">
            <i class="fa fa-info-circle"></i>
            General Info
        </a>
    </li>
    <li role="presentation">
        <a href="#companydetails" aria-controls="home" role="tab" data-toggle="tab">
            <i class="fa fa-info-circle"></i>
            Contact Details
        </a>
    </li>       
    <li class="divider"></li>

}


@{ Html.RenderPartial("UserResponses", Model.Responses); }

@using (Html.BeginForm("EditAction", "Members", FormMethod.Post, new { name = "editForm" }))
{
    @Html.HiddenFor(x =>x.Member.Id)
    @Html.HiddenFor(x => x.Member.Password)
    @Html.HiddenFor(x => x.Member.IsActivated)
    @Html.HiddenFor(x => x.Member.CreatedOn)
    <div class="row">        
        <div class="page-header">
            <h1>
                Editing @Model.Member.Firstname @Model.Member.Surname 
            </h1>
        </div>

        <div id="row">

            <div class="affix-row row">
                @if (!string.IsNullOrEmpty(Model.Member.Id))
                {
                    <div class="form-group pull-left">
                        <div class="form-group col-md-12">
                            <label class="control-label">
                                Member Status
                            </label>
                            <div>
                                <select class="form-control" id="listingStatus" name="Member.Status" autofocus>
                                    @foreach (PublicationStatus val in Enum.GetValues(typeof(PublicationStatus)))
                                    {
                                        if (Model.Member.Status == val)
                                        {
                                            <option selected="selected" value="@val.ToString()">@val.ToString()</option>
                                        }
                                        else
                                        {
                                            <option value="@val.ToString()">@val.ToString()</option>
                                        }
                                    }
                                </select>
                            </div>                    
                        </div>
                    </div>
                }
                <div class="pull-right">

                    <label class="control-label">
                        &nbsp;
                    </label>
                    <div class="btn-group pull-left margin-right-10">

                        <input class="btn btn-default btn-lg" id="cancel" name="submit" type="submit" value="Cancel" />

                        <input class="btn btn-primary btn-lg" id="save" name="submit" type="submit" value="Save" />

                    </div>


                </div>
            </div>
        </div>

        <div class="clearfix"></div>
        @if (Model.Member.CreatedBy != null)
        {
            <strong>
                Created by
            </strong>
            <text>@Model.Member.CreatedBy.Forename @Model.Member.CreatedBy.Surname on @Model.Member.CreatedOn.ToString("dd MMMM yyyy")</text>
        }
        @if (Model.Member.UpdatedBy != null)
        {
            <strong>Last updated by</strong>
            <text>@Model.Member.UpdatedBy.Forename @Model.Member.UpdatedBy.Surname on @Model.Member.UpdatedOn.ToString("dd MMMM yyyy")</text>
        }
        <div class="tab-content row">           

            <div class="clearfix"></div>

            <div role="tabpanel" class="tab-pane active" id="info">
                <h2>
                    General Info
                </h2>                               
                <ul class="list-unstyled">          
                    <li class="form-group">
                        <label>
                            Account Type
                        </label>
                        @Model.Member.AccountType
                        <select class="form-control" id="accountType" name="Member.AccountType" autofocus>
                            @foreach (AccountType val in Enum.GetValues(typeof(AccountType)))
                            {
                                if (Model.Member.AccountType == val)
                                {
                                    <option selected="selected" value="@val.ToString()">@val.ToString()</option>
                                }
                                else
                                {
                                    <option value="@val.ToString()">@val.ToString()</option>
                                }
                            }
                        </select>

                    </li>          
                    <li class="form-group">
                        @*maxchars" maxchars="110"*@
                        <label for="title">
                            Title<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Title)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Title, new { @class = "form-control", autofocus = string.Empty })
                    </li>
                    <li class="form-group">                    
                        <label for="firstname">
                            First Name<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Firstname)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Firstname, new { @class = "form-control", autofocus = string.Empty })
                    </li>                  
                    <li class="form-group">                        
                        <label for="surname">
                            Last Name<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Surname)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Surname, new { @class = "form-control", autofocus = string.Empty })
                    </li>                  
                    <li class="form-group">
                        <label for="email">
                            Email<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Email)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Email, new { @class = "form-control", autofocus = string.Empty })
                    </li>                                                       
                    <li class="form-group">
                        <label for="Telephone">
                            Phone Number<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Telephone)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Telephone, new { @class = "form-control", autofocus = string.Empty })
                    </li>    
                    <li class="form-group">
                        <label for="CompanyName">
                            Company Name<span class="required_star">*Required for Company Representatives</span> @Html.ValidationMessageFor(x => x.Member.CompanyName)
                        </label>
                        @Html.TextBoxFor(x => x.Member.CompanyName, new { @class = "form-control", autofocus = string.Empty })
                    </li>                                    
                    <li class="form-group">
                        <label for="Country">
                            Company Description<span class="required_star">*Required for Company Representatives</span> @Html.ValidationMessageFor(model => model.Member.CountryId)
                        </label>
                        @Html.TextAreaFor(x => x.Member.CompanyDescription, new { @class = "form-control" })
                    </li>                                                                                                        
                </ul>

            </div>
            <div id="companydetails" class="tab-pane">
                <h2>
                    Contact Details
                </h2>
                <ul class="list-unstyled">
                    <li class="form-group">
                        <label for="Address1">
                            Address 1<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Address1)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Address1, new { @class = "form-control", autofocus = string.Empty })
                    </li>                      
                    <li class="form-group">
                        <label for="Address2">
                            Address 2<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Address2)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Address2, new { @class = "form-control", autofocus = string.Empty })
                    </li>                  
                    <li class="form-group">
                        <label for="Address3">
                            Address 3<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Address3)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Address3, new { @class = "form-control", autofocus = string.Empty })
                    </li>                                                              
                    <li class="form-group">
                        <label for="Address4">
                            Address 4<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Address4)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Address4, new { @class = "form-control", autofocus = string.Empty })
                    </li>       
                    <li class="form-group">
                        <label for="Town">
                            Town<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Town)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Town, new { @class = "form-control", autofocus = string.Empty })
                    </li>                                                                                                      
                    <li class="form-group">
                        <label for="County">
                            County<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.County)
                        </label>
                        @Html.TextBoxFor(x => x.Member.County, new { @class = "form-control", autofocus = string.Empty })
                    </li>
                    <li class="form-group">
                        <label for="Country">
                            Country<span class="required_star">*</span> @Html.ValidationMessageFor(model => model.Member.CountryId)
                        </label>
                        @Html.DropDownListFor(model => model.Member.CountryId, new SelectList(ViewBag.Countries, "Value", "Text", Model.Member.CountryId), "--Choose One--",
                            new { @class = "form-control", @title = "Select Country" })
                    </li>                                    

                    <li class="form-group">
                        <label for="PostCode">
                            Post Code<span class="required_star">*</span> @Html.ValidationMessageFor(x => x.Member.Postcode)
                        </label>
                        @Html.TextBoxFor(x => x.Member.Postcode, new { @class = "form-control", autofocus = string.Empty })
                    </li>
                                                                                                                                                                                                                              
                </ul>
            </div>
            
        </div>
        
    </div>
}

Supplier_Directory/CMS/Views/Members/MemberList.cshtml
@using CMS.Helpers
@using SD.Core.Common.Constants
@using SD.Core.Common.Utils
@using SD.Core.Services.Security
@using SD.Core.Data.Model
@model IList<Member>
@if (Model != null && Model.Count != 0)
{
    foreach (var member in Model)
    {
        <div class="list-group-item">

            <div class="btn-group pull-right" role="group">
                @if (member.Status != PublicationStatus.Deleted)
                {

                    <a class="btn btn-default" href="@Url.Action("Edit", "Members", new { id = member.Id })" title="View Members">
                        <i class="fa fa-eye" title="View Member"></i>
                    </a>



                    <a class="btn btn-default" href="@Url.Action("Edit", "Members", new { id = member.Id })" title="Edit">
                        <i class="fa fa-pencil" title="Edit"></i>
                    </a>

                    if (LiveUser.Can(Permission.EditArticles))
                    {
                        @*<a class="btn btn-danger" href="@Url.Action("Delete", "Members", new { id = Model.Id })" title="Delete">
                                <i class="fa fa-trash" title="Delete"></i>
                            </a>*@
                    }

                }
                else
                {
                    if (LiveUser.Can(Permission.EditArticles))
                    {

                        <a class="btn btn-default" href="/Members/HardDelete?articleid=@member.Id" title="Remove from recycle bin (irreversible)">
                            <i class="fa fa-exclamation-triangle"></i>
                        </a>

                        <a class="btn btn-default" href="/Members/Restore?articleid=@member.Id" title="Restore">
                            <i class="fa fa-repeat"></i>
                        </a>
                    }
                }
            </div>

            <h4>
                @member.Title @member.Firstname @member.Surname <br />
                <small>@member.Email</small>
            </h4>

            <ul class="list-unstyled">
                <li class="form-group">
                    <strong>
                        @member.Status
                    </strong>
                </li>
                <li class="divider"></li>
                <li class="col-md-3 col-sm-2 ">
                    <i class="fa fa-calendar"></i>

                    Created On: @(((DateTime)member.CreatedOn).ToLocalTime())
                </li>
                <li class="col-md-3 col-sm-2 ">
                    <i class="fa fa-calendar"></i>

                    Updated On: @(((DateTime)member.UpdatedOn).ToLocalTime())
                </li>
            </ul>

        </div>
    }
}
else
{
    <li>
        No members
    </li>
}

Supplier_Directory/CMS/Views/Members/MemberListItem.cshtml
@using CMS.Helpers
@using SD.Core.Common.Constants
@using SD.Core.Common.Utils
@using SD.Core.Services.Security
@using SD.Core.Data.Model
@model Member

<div class="list-group-item">

    <div class="btn-group pull-right" role="group">
        @if (Model.Status != PublicationStatus.Deleted)
        {

            <a class="btn btn-default" href="@Url.Action("Edit", "Members", new { id = Model.Id })" title="View Members">
                <i class="fa fa-eye" title="View Member"></i>
            </a>



            <a class="btn btn-default" href="@Url.Action("Edit", "Members", new { id = Model.Id })" title="Edit">
                <i class="fa fa-pencil" title="Edit"></i>
            </a>

            if (LiveUser.Can(Permission.EditArticles))
            {
                @*<a class="btn btn-danger" href="@Url.Action("Delete", "Members", new { id = Model.Id })" title="Delete">
                        <i class="fa fa-trash" title="Delete"></i>
                    </a>*@
            }

        }
        else
        {
            if (LiveUser.Can(Permission.EditArticles))
            {

                <a class="btn btn-default" href="/Members/HardDelete?articleid=@Model.Id" title="Remove from recycle bin (irreversible)">
                    <i class="fa fa-exclamation-triangle"></i>
                </a>

                <a class="btn btn-default" href="/Members/Restore?articleid=@Model.Id" title="Restore">
                    <i class="fa fa-repeat"></i>
                </a>
            }
        }
    </div>

    <h4>
        @Model.Title @Model.Firstname @Model.Surname <br />
        <small>@Model.Email</small>
    </h4>

    <ul class="list-unstyled">
        <li class="form-group">
            <strong>
                @Model.Status
            </strong>
        </li>
        <li class="divider"></li>
        <li class="col-md-3 col-sm-2 ">
            <i class="fa fa-calendar"></i>

            Created On: @(((DateTime)Model.CreatedOn).ToLocalTime())
        </li>
        <li class="col-md-3 col-sm-2 ">
            <i class="fa fa-calendar"></i>

            Updated On: @(((DateTime)Model.UpdatedOn).ToLocalTime())
        </li>               
    </ul>

</div>